name: to_do_list_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  awesome_bottom_bar: ^1.2.4
  awesome_dialog: ^3.1.0
  bloc: ^8.1.2
  chips_choice: ^3.0.1
  contained_tab_bar_view: ^0.8.0
  dartz: ^0.10.1
  day_night_time_picker: ^1.0.5
  device_preview: ^1.1.0
  dio: ^5.3.2
  equatable: ^2.0.5
  flex_color_scheme: ^7.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_custom_clippers: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^15.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.4
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^3.0.0
  font_awesome_flutter: ^10.5.0
  get: ^4.6.5
  google_fonts: ^5.1.0
  hive: ^2.2.3
  hive_flutter: any
  hive_generator: any
  intl: ^0.18.0
  introduction_screen: ^3.1.11
  json_annotation: ^4.8.1
  liquid_swipe: ^3.1.0
  lottie: ^2.6.0
  mocktail: ^1.0.0
  remixicon: ^1.0.0
  shared_preferences: ^2.2.2
  show_up_animation: ^2.0.0
  sizer: ^2.0.15
  swipeable_page_route: ^0.4.0
  time_picker_sheet: ^0.0.2+1
  timelines: ^0.1.0
  timezone: ^0.9.2

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1

  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  very_good_analysis: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/images/ic_launcher.png"

flutter_native_splash:
  color: "#ffffff"
  android: true
  ios: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/lotties/
    - assets/images/
